repos:
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: make lint
        language: system
        types: [python]
      - id: fmt
        name: fmt
        entry: make fmt
        language: system
        types: [python]
      - id: tests
        name: test local
        entry: make test
        language: system
        pass_filenames: false
        types: [python]