services:
  app:
    build:
      context: .
      target: app
    restart: always
    ports:
      - $APP_PORT:$APP_PORT
    command: python -m src.presentation.http.app
    env_file:
      - local.env
    depends_on:
      - db

  db:
    image: mongo:latest
    restart: always
    ports:
      - $MONGODB_PORT:$MONGODB_PORT
    env_file:
      - local.env
    volumes:
      - db-logs:/var/log/mongodb/
      - ./infra/docker/mongo/init_mongo.js:/docker-entrypoint-initdb.d/init_mongo.js:ro


volumes:
  db-data:
    driver: local
    name: mongo-data
  db-logs:
    driver: local
    name: mongo-logs
