[tool.ruff]
select = ["E", "F", "B", "UP", "SIM"]
ignore = []
fix = false

extend-exclude = [
    "tests"
]

line-length = 120
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

target-version = "py311"

[tool.ruff.flake8-bugbear]
extend-immutable-calls = ["fastapi.Depends", "fastapi.Query", "fastapi.Body", "fastapi.Path"]

[tool.ruff.mccabe]
max-complexity = 10

[tool.black]
line-length = 120
target-version = ['py311']

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
asyncio_mode = "auto"
