global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  # - job_name: "prometheus"
  #   honor_timestamps: true
  #   scrape_interval: 15s
  #   scrape_timeout: 10s
  #   metrics_path: /metrics
  #   scheme: http
  #   follow_redirects: true
  #   enable_http2: true
  #   static_configs:
  #     - targets:
  #         - prometheus:9090
  - job_name: "timeapp"
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets:
          - app:8000
