server:
  http_listen_port: $LOKI_PORT
  grpc_listen_port: $LOKI_GRPC_PORT


ingester:
  lifecycler: # параметры журнала
    address: $LOKI_HOST 
    ring: 
      kvstore: # тип хранилища
        store: memcached # хранить в памяти, можно подрубить БД, к примеру S3
        memcached:
          addresses:
           - $LOKI_HOST:$LOKI_PORT

chunk_store: # хранение и управление фрагментами журналов (сжатые, индексированные данные)
  chunk_cache_config: # конфиги кэша фрагментов
    max_lookups: 0 # макс кол-во поисковых запросов для поиска фрагментов. 0 - все фрагменты доступны
    max_size: 536870912 # дефолт в MB. Можно изменить суффиксом: KB, MB, GB
    max_age: 0s # без ограничения времени. Можно установить суффиксы s, m, h, d


schema_config: # настройка схемы для хранения и индексации журналов: какие данные журналов организованы и как доступные для поиска и анализа
  configs:
    - from: 2020-01-01 # начала применения конфигурация схемы
      store: boltdb # встраиваемая база данных на диске
      object_store: filesystem # тип хранилища обьектов (gcs, s3, filesystem)
      schema: v11
      index:
        prefix: index_
        period: 168h # Период хранения индексации


# auth_enabled: false
# auth_config:
#   backend: basic
#   basic_auth:
#     users:
#       - username: $LOKI_USERNAME
#         password: $LOKI_PASSWORD


# ruler:
#   alertmanager_url: $LOKI_ALERT_MANAGER_HOST:$LOKI_ALERT_MANAGER_PORT